!!es.um.poa.agents.seller.SellerAgentConfig
cif: "SE004"
nombre: "Pedro Sanchez"
listaPescado:
  - nombre: "sardina"
    tipoProducto: "pescado azul"
    peso: 4.87
    precioReserva: 1.3
  - nombre: "boqueron"
    tipoProducto: "marisco"
    peso: 7.23
    precioReserva: 8.97