!!es.um.poa.agents.seller.SellerAgentConfig
cif: "SE004"
nombre: "Pedro Sanchez"
listaPescado:
  - nombre: "sardina"
    tipoProducto: "pescado gris"
    peso: 4.87
    precioReserva: 1.3
  - nombre: "lubina"
    tipoProducto: "pescado azul"
    peso: 2.23
    precioReserva: 7.97
  - nombre: "boqueron"
    tipoProducto: "marisco"
    peso: 2.23
    precioReserva: 2.97