!!es.um.poa.agents.seller.SellerAgentConfig
cif: "SE206"
nombre: "Paco Gerte"
listaPescado:
  - nombre: "sardina"
    tipoProducto: "pescado gris"
    peso: 1.87
    precioReserva: 1.3
  - nombre: "merluza"
    tipoProducto: "pescado azul"
    peso: 2.02
    precioReserva: 5.04
